-- =====================================================================
-- SQL Script: Migrate from Lemon Squeezy to Stripe in Supabase
-- Target Database: Supabase Dev Database
-- =====================================================================

-- 1. Add Stripe tracking columns to public.companies table
ALTER TABLE public.companies 
ADD COLUMN IF NOT EXISTS stripe_customer_id text,
ADD COLUMN IF NOT EXISTS stripe_subscription_id text;

COMMENT ON COLUMN public.companies.stripe_customer_id IS 'Unique customer ID generated by Stripe (cus_...)';
COMMENT ON COLUMN public.companies.stripe_subscription_id IS 'Active subscription ID generated by Stripe (sub_...)';

-- 2. Clean up legacy Lemon Squeezy columns
ALTER TABLE public.companies 
DROP COLUMN IF EXISTS lemon_squeezy_customer_id,
DROP COLUMN IF EXISTS lemon_squeezy_subscription_id;

-- 3. Ensure indexes exist for fast customer & company subscription lookups
CREATE INDEX IF NOT EXISTS idx_companies_stripe_customer_id ON public.companies (stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_companies_stripe_subscription_id ON public.companies (stripe_subscription_id);

-- 4. RPC Function to safely update subscription status via webhooks/edge functions
CREATE OR REPLACE FUNCTION update_company_stripe_subscription(
  p_company_id uuid,
  p_stripe_customer_id text,
  p_stripe_subscription_id text,
  p_subscription_level text,
  p_subscription_status text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.companies
  SET 
    stripe_customer_id = COALESCE(p_stripe_customer_id, stripe_customer_id),
    stripe_subscription_id = COALESCE(p_stripe_subscription_id, stripe_subscription_id),
    subscription_level = p_subscription_level,
    subscription_status = p_subscription_status,
    updated_at = NOW()
  WHERE id = p_company_id;

  RETURN FOUND;
END;
$$;
