-- =====================================================================
-- SQL Script: Add Lemon Squeezy subscription columns to the companies table
-- Run this script in the Supabase SQL Editor to upgrade your schema.
-- =====================================================================

ALTER TABLE public.companies 
ADD COLUMN IF NOT EXISTS lemon_squeezy_customer_id text,
ADD COLUMN IF NOT EXISTS lemon_squeezy_subscription_id text;

-- Add a comment on these columns for future reference
COMMENT ON COLUMN public.companies.lemon_squeezy_customer_id IS 'Unique customer ID generated by Lemon Squeezy';
COMMENT ON COLUMN public.companies.lemon_squeezy_subscription_id IS 'Active subscription ID generated by Lemon Squeezy';
